from abc import ABC, abstractmethod
from typing import Optional

class LLMProvider(ABC):
    """
    Abstract Base Class for LLM providers in Problem Foundry.
    Model-agnostic design allowing runtime switching between Ollama,
    LM Studio, vLLM, and OpenAI-compatible local APIs.
    """

    @abstractmethod
    async def generate(self, prompt: str, system: Optional[str] = None) -> str:
        """
        Generate raw text or structured JSON text from the local LLM.

        Args:
            prompt: The user instruction / structured prompt.
            system: Optional system instruction for role framing.

        Returns:
            The raw response string generated by the model.
        """
        pass

    @abstractmethod
    async def test_connection(self) -> bool:
        """
        Check if the local provider endpoint is reachable and healthy.
        """
        pass
